### PR TITLE
Add map

### PR DESCRIPTION
**Pull request by Zoe9711**
Add a basic map with javascript api enabled, centered in San Francisco

### CODE REVIEW

**Review by jasmine-r — APPROVED** [review]
LGTM

**Review by neekssss — COMMENTED** [review]
LGTM, let's have either Sam or Ashwin to take a look at it before merging.

**Comment by Zoe9711** [comment]
> LGTM, let's have either Sam or Ashwin to take a look at it before merging.

cool. Is Ashwin added to our project?

**Comment by neekssss** [comment]
> > LGTM, let's have either Sam or Ashwin to take a look at it before merging.
> 
> cool. Is Ashwin added to our project?

The invitation has been sent to him, probably just busy for the time being.

On another note, i'm not sure if this will cause issues when merging, but both PR 7 and PR 8 are quite similar.

**Comment by Zoe9711** [comment]
> > > LGTM, let's have either Sam or Ashwin to take a look at it before merging.
> > 
> > 
> > cool. Is Ashwin added to our project?
> 
> The invitation has been sent to him, probably just busy for the time being.
> 
> On another note, i'm not sure if this will cause issues when merging, but both PR 7 and PR 8 are quite similar.

I think it should be fine. seems that Jasmine branched off from my branch

**Comment by jasmine-r** [comment]
Yes, I branched off Zoe's work with the map set-up since the task of setting markers was related to the map set up. 
I had similar PRs for the portfolio project, it'll be okay to go through

**Comment by neekssss** [comment]
> Yes, I branched off Zoe's work with the map set-up since the task of setting markers was related to the map set up.
> I had similar PRs for the portfolio project, it'll be okay to go through

All good then!

**Review by neekssss — APPROVED** [review]

**Pull request merged**
